### ISSUE TITLE
exploring rx: range-expression bug

### ISSUE THREAD

**Issue by bymoz089** [FrancisMurillo/francismurillo.github.io#1]
In your post
2017-03-30-Exploring Emacs rx Macro.html
is a bug within your range-expression.
your range expression matches all numbers and also IPs like 61.12.266.3000

(setq range-expression ;; Expression and pattern separated for reuse
      `(or "0"
           (sequence "1" (optional digit (optional digit)))
           (sequence "2" (optional
                          (or
                           (sequence (any "0-4") (optional digit))
                           (sequence "5" (optional (any "0-5")))
                           (sequence (any "6-9")))))
           (sequence (any "3-9") (optional digit))))

(setq range-pattern (rx bol
						(eval range-expression)
						eol))

(setq ip4-pattern (rx bol
					  (repeat 3 (sequence (eval range-expression) "."))
                      (eval range-expression)
					  eol))

above would be better. Most probably you com up with a better solution.

**Comment by FrancisMurillo** [comment]
Sorry for the long reply. Was planning to finally overhaul with a new design then I noticed this issue.

Anyway, the fix is easy 

```
(setq ip4-pattern (rx bol
                      (repeat 3 (sequence (eval range-expression) "."))
                      (eval range-expression)
                      eol))
```

We just add an `bol` and `eol` for the pattern. Didn't consider that case, so thanks for pointing that out. When I update my page, I'll update the code with the new fix.

**Comment by FrancisMurillo** [comment]
Updated my post with the fix at last. Again, thanks for pointing it out and I'll be closing this one now.
